# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

env:
  global:
    # Enable vignette building:
    - R_BUILD_ARGS="--no-manual"
    # Disable this until the dust settles:
    # - WARNINGS_ARE_ERRORS=1

sudo: required

# For testing against and using RcppRedis
services:
  - redis-server

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libhiredis-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r rmarkdown
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
